apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ws-assets
  name: ws-assets
spec:
  containers:
    - env:
        - name: WS_ASSETS_ENABLE_UI
          value: "TRUE"
        - name: WS_ASSETS_LOG_LEVEL
          value: DEBUG
        - name: WS_ASSETS_POSTGRESQL_DSN
          value: postgresql+asyncpg://user:password@postgresql:5432/database
      image: ws_assets:latest
      name: ws_assets
      ports:
        - containerPort: 8080
      resources: {}
  restartPolicy: OnFailure
status: {}
